name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        cd src 
        cd UsefullEndpoints
        dotnet tool restore
        dotnet r pack   
    # - name: Restore dependencies
    #   run: |
    #     cd src 
    #     cd UsefullEndpoints
    #     dotnet tool restore
    #     dotnet pwsh readme.ps1        
    #     dotnet restore
    # - name: Build
    #   run: |
    #     cd src
    #     cd UsefullEndpoints
        
    #     dotnet build --no-restore
    # - name: Pack
    #   run: |
    #     cd src
    #     cd UsefullEndpoints
    #     cd UsefullExtensions
    #     dotnet pack -o ../nugetPackages  --include-symbols --include-source

    - name: 'Upload nuget'
      #if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/upload-artifact@v2
      with:
        name: UsefullEndpoints_${{github.run_number}}
        path: src/UsefullEndpoints/nugetPackages
        retention-days: 1
