name: Build nuget package

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    
    - name: Set up .NET Core 9
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget

    - name: Restore dependencies
      run: |
        cd src 
        cd UsefullEndpoints
        dotnet tool restore
        dotnet r make_readme
        dotnet r pack   
    # - name: Restore dependencies
    #   run: |
    #     cd src 
    #     cd UsefullEndpoints
    #     dotnet tool restore
    #     dotnet pwsh readme.ps1        
    #     dotnet restore
    # - name: Build
    #   run: |
    #     cd src
    #     cd UsefullEndpoints
        
    #     dotnet build --no-restore
    # - name: Pack
    #   run: |
    #     cd src
    #     cd UsefullEndpoints
    #     cd UsefullExtensions
    #     dotnet pack -o ../nugetPackages  --include-symbols --include-source

    - name: 'Upload nuget'
      #if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/upload-artifact@v4
      with:
        name: UsefullEndpoints_${{github.run_number}}
        path: src/UsefullEndpoints/nugetPackages
        retention-days: 1