name: Build and deploy to Azure Web App and nuget

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up .NET Core 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          


      - name: Set up .NET Core 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'


      - name: Set up .NET Core 8
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Set up .NET Core 9
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x'
  
      - name: Build with dotnet
        run: |
          cd src
          cd UsefullEndpoints
          dotnet build --configuration Release

      - name: dotnet publish
        run: |
          cd src
          cd UsefullEndpoints
          cd TestUsefullEndpoints
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: deploy to nuget
        run: |
          cd src 
          cd UsefullEndpoints
          dotnet tool restore
          dotnet r make_readme
          dotnet r pack   

      - name: push to nuget
        run: |
            dotnet nuget push ${{github.workspace}}/src/UsefullEndpoints/nugetPackages/*symb*.*pkg --api-key  ${{ secrets.NUGETAPIKEY }} --source https://api.nuget.org/v3/index.json

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'NetCoreUsefullEndpoints'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_85E905652D3443429F3F85D84362553C }}
          package: .
